#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Mission\Impossible\Command\GetMissions;
use Mission\Impossible\Command\NextMissions;
use Mission\Impossible\Command\PrevMissions;
use Mission\Impossible\Command\GetMissionsByCommand;
use Mission\Impossible\Command\GetMissionsByEvent;
use Mission\Impossible\Command\GetMissionsByStatus;
use Symfony\Component\Console\Application;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\DependencyInjection\Reference;

$container = new ContainerBuilder();
$container->register('parser', 'Parser');
$container->register('sorter', 'Sorter');

$container->register('mission', 'Mission')
    ->addArgument(new Reference('parser'))
    ->addArgument(new Reference('sorter'));

$container->compile();

$application = new Application();
$application->add(new GetMissions($container->get('parser'),$container->get('sorter')));
$application->add(new NextMissions($container->get('parser'),$container->get('sorter')));
$application->add(new PrevMissions($container->get('parser'),$container->get('sorter')));
$application->add(new GetMissionsByCommand($container->get('parser'),$container->get('sorter')));
$application->add(new GetMissionsByEvent($container->get('parser'),$container->get('sorter')));
$application->add(new GetMissionsByStatus($container->get('parser'),$container->get('sorter')));
$application->run();