name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - uses: php-actions/composer@v6
      - run: echo "Run static analysis"
      - run: ./vendor/bin/php-cs-fixer fix  --diff --dry-run
      - run: echo "Run unit tests"
      - run: ./vendor/bin/phpunit test